#!/bin/sh

SKINDIR='/usr/share/enigma2/Luka-FHD-PLI'
MCDIR='/usr/share/enigma2/Luka-FHD-PLI/main/maincolor'
TMPDIR='/tmp'
BOXMODEL=$(cat /etc/hostname)
set -e
echo "Supported Images are : "
echo "1- OpenPLI develop , OpenPLI 9 , OpenPLI 10 , OpenPLI 10.1"
echo "2- OBH 5.3 , 5.4 , 5.4.1 , 5.5.x , 5.6"
echo "3- OpenVIX 6.4 , 6.5 , 6.6 , 6,7 , 6.8"
echo "4- NonSoloSat"
echo "5- OpenTR"
echo "6- SatLodge"
echo "7- CobraliberoSat"
echo "8- TeamBlue 7.3 , 7.4 , 7.5"
echo "9- OpenPLI foxbob python 3.13"
echo "10- Corvoboys"
echo "11- TNAP"
sleep 2
echo "Copying Crimson backgrounds ...."
cp $MCDIR/lkimages_crimson_blue/2ndinfobar3.png $SKINDIR/lkimages/2ndinfobar3.png
cp $MCDIR/lkimages_crimson_blue/ch_bg.jpg $SKINDIR/lkimages/ch_bg.jpg
cp $MCDIR/lkimages_crimson_blue/infobar.png $SKINDIR/lkimages/infobar.png
cp $MCDIR/lkimages_crimson_blue/menu_bg.png $SKINDIR/lkimages/menu_bg.png
echo "Identify your image ...."
sleep 2

# Function to replace StartTime with Times
replace_eventtime() {
    echo "Making some adjustiments..."
    for f in \
        /usr/lib/enigma2/python/Plugins/Extensions/Luka/sample/secondinfobar-secondinfobar_base1.xml \
        /usr/lib/enigma2/python/Plugins/Extensions/Luka/sample/eventview-eventview_1_poster.xml \
        /usr/lib/enigma2/python/Plugins/Extensions/Luka/sample/eventview-eventview_NO_poster.xml \
        /usr/share/enigma2/Luka-FHD-PLI/skin_templates.xml
    do
        if [ -f "$f" ]; then
            sed -i 's|<convert type="EventTime">StartTime</convert>|<convert type="EventTime">Times</convert>|g' "$f"
        fi
    done
}

if grep -qs -i "openbh" /etc/image-version; then
    echo "You have Openbh image"
    echo "Adjusting some files according to your image..."
    mv $SKINDIR/image_logo/obh/imagelogo.png $SKINDIR
    replace_eventtime

elif grep -qs -i "openvix" /etc/image-version; then
    echo "You have OpenVix image"
    echo "Adjusting some files according to your image..."
    mv $SKINDIR/image_logo/openvix/imagelogo.png $SKINDIR
    replace_eventtime

elif grep -qs -i "openpli" /etc/issue; then
    if grep -qs -i "GCC-15" /etc/issue; then
        echo "You have OpenPli GCC-15.1 image"
        echo "Adjusting some files according to your image..."		
        mv $SKINDIR/image_logo/openplifoxbob/imagelogo.png $SKINDIR
        replace_eventtime
    else
        echo "You have OpenPli image"
        echo "Adjusting some files according to your image..."		
        mv $SKINDIR/image_logo/openpli/imagelogo.png $SKINDIR
    fi

elif grep -qs -i "foxbob" /etc/issue; then
    echo "You have OpenPli foxbob image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/openplifoxbob/imagelogo.png $SKINDIR
    replace_eventtime

elif grep -qs -i "corvoboys" /etc/image-version; then
    echo "You have CorvoBoys image"
    echo "Adjusting some files according to your image..."
    mv $SKINDIR/image_logo/corvoboys/imagelogo.png $SKINDIR
    mv $SKINDIR/image_logo/corvoboys/picon_default.png $SKINDIR
    rm -rf $SKINDIR/spinner > /dev/null 2>&1
    rm -rf $SKINDIR/picon_default.png  > /dev/null 2>&1
    cp $SKINDIR/sf/little_logo.png $SKINDIR/picon_default.png

elif grep -qs -i "TNAP" /etc/issue; then
    echo "You have TNAP image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/tnap/imagelogo.png $SKINDIR

elif grep -qs -i "opentr" /etc/issue; then
    echo "You have OpenTR image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/opentr/imagelogo.png $SKINDIR

elif grep -qs -i "areadeltasat" /etc/issue; then
    echo "You have areadeltasat image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/openpli/imagelogo.png $SKINDIR

elif grep -qs -i "teamblue" /etc/issue; then
    echo "You have TeamBlue image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/teamblue/imagelogo.png $SKINDIR

elif grep -qs -i "nonsolosat" /etc/issue; then
    echo "You have NonSoloSat image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/nss/imagelogo.png $SKINDIR

elif grep -qs -i "cobraliberosat" /etc/issue; then
    echo "You have CobraliberoSat image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/cobra/imagelogo.png $SKINDIR

elif grep -qs -i "satlodge" /etc/issue; then
    echo "You have SatLodge image"
    echo "Adjusting some files according to your image..."		
    mv $SKINDIR/image_logo/satlodge/imagelogo.png $SKINDIR

else	
    echo "even you do not have supported image , you can try Luka-FHD-PLI"
fi

sleep 2
echo "removing some files.... "
rm -rf $SKINDIR/image_logo  > /dev/null 2>&1
rm -rf /control  > /dev/null 2>&1
echo "enigma2-plugin-skins-luka-fhd-pli was installed successfully "
sleep 2
set +e
sleep 2
echo ">>>>>>>>>>>>>>>>>>>DONE<<<<<<<<<<<<<<<<<<<<<"
sleep 2
echo ">>>>>>>>>>Luka-FHD-PLI Skin by MNASR<<<<<<<<<<"
sleep 2
exit 0
